# Set to other image if needed
FROM vllm/vllm-openai:v0.9.2

ARG PIP_INDEX_URL="https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple"

WORKDIR /workspace

# Install unified-cache-management
COPY . /workspace/unified-cache-management

RUN pip config set global.index-url ${PIP_INDEX_URL}

RUN export PLATFORM="cuda" && \
     pip install -v -e /workspace/unified-cache-management --no-build-isolation

ENTRYPOINT ["/bin/bash"]